// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// jqr
std::string jqr(std::string json, std::string program);
RcppExport SEXP jqr_jqr(SEXP jsonSEXP, SEXP programSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< std::string >::type json(jsonSEXP );
        Rcpp::traits::input_parameter< std::string >::type program(programSEXP );
        std::string __result = jqr(json, program);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
